### ISSUE TITLE
Numbers and Units Don't Align

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk-browser#17]
Quantities are now displayed in two parts:  the numeric value and the units.  Only the units are hyperlinked, not the values. On the React-based browser, the numbers and the units do not align when displayed.

**Comment by CraigMiloRogers** [comment]
I spend about 4 hours trying to solve this.  I learned a bit about React and the Material Design, but did not find a fix.  I used Firefox on Linux, I should take a look using a different browser/OS combination.

**Comment by g1eb** [comment]
No worries, I'll take a look. What is a good node to use for testing?

I think I would need to get that sqlite database with the wikidata (or a different graph that has nodes with quantities)
@CraigMiloRogers what's the easiest way to get that database?

**Comment by CraigMiloRogers** [comment]
Q30 shows it first in the `area` property.  I'll look for an example that loads more quickly.

**Comment by CraigMiloRogers** [comment]
I've confirmed that the problem exists when running a Web browser on Windows 10.  I tested using the latest versions of Firefox, Chrome, and Edge.

**Comment by g1eb** [comment]
Could you share a screenshot of where this alignment issue occurs?
Or we can do a quick zoom call with screen share, I just want to make sure I'm looking in the right place.

**Comment by CraigMiloRogers** [comment]
You should be able to access ckg07:/data/rogers/faast-kg-building/wikidata-and-tdm-and-factset/FactSet_TDM_Wikidata.all.sqlite3.db

**Comment by CraigMiloRogers** [comment]
I'm in another zoom conference now.  I'll ping you on slack.

**Comment by g1eb** [comment]
> You should be able to access ckg07:/data/rogers/faast-kg-building/wikidata-and-tdm-and-factset/FactSet_TDM_Wikidata.all.sqlite3.db

sweet! I'll try that one right now

**Comment by g1eb** [comment]
> I'm in another zoom conference now. I'll ping you on slack.

sounds good, let me know when is a good time for you

**Comment by CraigMiloRogers** [comment]
Gleb's changes fixed the alignment.

**Comment by CraigMiloRogers** [comment]
Changes committed to `dev`
