### ISSUE TITLE
Spacing Changes

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk-browser#21]
From @szeke :

Small format improvement for the browser: the qualifier values are too far to the right from the properties, please reduce. Same for the distance between properties and values. It is a bit hard for the eye to track. It is OK if some of the properties with long names wrap to two lines

**Comment by g1eb** [comment]
We looked into this change on a zoom call just now and Pedro said to leave it as is for now (might need to reopen the issue later if that decision changes).
