### ISSUE TITLE
Incoming Edges

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk-browser#33]
From @szeke :

@Gleb @craigmilorogers The next feature that we should add to the browser is the incoming edges. Below are two links for how other browsers do this, SQID and Reasonator. Both include a section for incoming edges From related entities. In SQID it is a separate tab and in Reasonataor it is a separate section. I like the Reasonator solution where they have multiple sections, and From related entities is one of six sections. Each section is collapsible.

I like th visual appearance in SQID where they show an arrow pointing to the left to remind you that the edge is incoming. Otherwise the display looks identical to the outgoing edges and it is easy to get confused: https://sqid.toolforge.org/#/view?id=Q30

Reasonator also has a timeline section which combines all the statements with time qualifiers. It is an interesting idea, but doesn’t quite cut it for me as there is too much text to read. I think havinf a stack of sparklines would be nicer.

@Gleb Can you create a revision to the react code that allows us to have collapsible sections. For starters we would have two sections.

1.    Properties which contains the statements we have now
2.    From related entities where we put the incoming edges.

@craigmilorogers we have to be careful with the queries for incoming edges as there can be many thousands of them. I think we should not even query for all of them, even if this means doing separate queries. We can profile the KG to see which properties may have too many incoming edges and query them separately with a limit.

**Comment by g1eb** [comment]
@CraigMiloRogers , let’s set up a meeting sometime this week to discuss the incoming edges api. What day and time would work best for you this week?

PS. We can also look into serving the frontend from the distribution folder instead of the source - is there a ticket for that already?

**Comment by szeke** [comment]
Let's start simple. We want to have sections, so @g1eb please design the react that can have sections that can be opened and closed. For the API, this is @CraigMiloRogers task, there should be an endpoint that returns a JSON in the same format as the current one, and it includes some incoming edges. Once we have that, we can refine.

**Comment by g1eb** [comment]
The sections are now expandible/collapsible, and there is a placeholder for the "From related items".

**Comment by saggu** [comment]
THe endpoints for related items is implemented and is merged into `main` branch. Changes are deployed in KGTK browser as well
