### ISSUE TITLE
Experiment with Alternate Searches

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk-browser#51]
Create a testbed and experiment with alternate searches.

One focus will be to test the features and performance of the textmatch functionality in kypher.

Another focus will be to prejoin label, pagerank, and description for enhanced search.

select node1, label, pagerank, description
from searchtable
where textmatch(upper_case_label)
order by pagerank, label
limit 20 # in practice, a variable that can be changed in the query API.

We want to compare the functionality and performance of the current search (glob), the current search
with a leading `*`, the various forms of textmatch, and the elastic search server.

**Comment by saggu** [comment]
Done, closing
