### ISSUE TITLE
The `blue` and `orange` colors in the visualization graph should be consistent

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk-browser#63]
Right now, sometimes `few_classes` is assigned orange and `many_classes` is assigned blue and vice versa.

We should sort the list by the `color column` and then assign colors

**Comment by g1eb** [comment]
The colors are currently handled in the backend, we could look into that to make sure they are more consistent. 

Current node will be colored green to indicate where the graph starts.

**Comment by saggu** [comment]
Pushed a hacky fix to achieve this, keeping this open until we have a proper solution

**Comment by g1eb** [comment]
Is this still relevant? I believe we changed the colors at some point.

**Comment by saggu** [comment]
Fixed using hex colors codes which are fixed
