### ISSUE TITLE
Handle High Cardinality Properties Specially

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk-browser#67]
In the initial query, do not return the values for high cardinality properties. Use a separate ajax interaction to page through the values.

**Comment by CraigMiloRogers** [comment]
https://docs.google.com/document/d/1qd2XgTZ81cLPY7qJMonI5bNXtx4ANFB0q2JZGI28Q3U/edit#

**Comment by saggu** [comment]
This change is complete.
